version: "3"

services:
  cloud-run-python-template:
    image: cloud-run-python-template
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - "8080:8080"
